In [2]:
import pandas as pd

In [3]:
sales_url = "https://api.iea.org/evs?parameters=EV%20sales&category=Historical&mode=Cars&csv=true"
sales_df = pd.read_csv(sales_url)


sales_df.head()

,region,category,parameter,mode,powertrain,year,unit,value
0,Australia,Historical,EV sales,Cars,BEV,2011,Vehicles,49.00000
1,Australia,Historical,EV stock share,Cars,EV,2011,percent,0.00039
2,Australia,Historical,EV sales share,Cars,EV,2011,percent,0.00650
3,Australia,Historical,EV stock,Cars,BEV,2011,Vehicles,49.00000
4,Australia,Historical,EV stock,Cars,BEV,2012,Vehicles,220.00000

In [4]:
def load_sales_data():
    sales_url = "https://api.iea.org/evs?parameters=EV%20sales&category=Historical&mode=Cars&csv=true"
    sales_df = pd.read_csv(sales_url)
    cleaned_sales_df = sales_df[sales_df["parameter"] == "EV sales"]
    cleaned_sales_df = cleaned_sales_df[cleaned_sales_df["powertrain"] == "BEV"]
    cleaned_sales_df.drop(['mode', 'powertrain', 'parameter', 'category', "unit"], axis=1, inplace=True)
    return cleaned_sales_df

    #alt: cols_to_keep = ['region', 'year', 'value']
    #cleaned_sales_df = cleaned_sales_df[cols_to_keep]

new_sales = load_sales_data()
new_sales.head(20)

        region  year    value
0    Australia  2011     49.0
9    Australia  2012    170.0
10   Australia  2013    190.0
21   Australia  2014    370.0
22   Australia  2015    760.0
33   Australia  2016    670.0
34   Australia  2017   1200.0
45   Australia  2018   1800.0
51   Australia  2019   6300.0
52   Australia  2020   5200.0
64   Australia  2021  17000.0
67   Australia  2022  33000.0
80   Australia  2023  87000.0
93     Austria  2013    650.0
94     Austria  2014   1700.0
108    Austria  2015   1700.0
109    Austria  2016   3800.0
123    Austria  2017   5400.0
124    Austria  2018   6800.0
139    Austria  2019   9300.0

In [5]:
charging_url = "https://api.iea.org/evs?parameters=EV%20charging%20points&category=Historical&mode=EV&csv=true"
charging_df = pd.read_csv(charging_url)

charging_df.head(20)

,region,category,parameter,mode,powertrain,year,unit,value
0,Australia,Historical,EV charging points,EV,Publicly available fast,2017,charging points,40.0
1,Australia,Historical,EV charging points,EV,Publicly available slow,2017,charging points,440.0
2,Australia,Historical,EV charging points,EV,Publicly available fast,2018,charging points,61.0
3,Australia,Historical,EV charging points,EV,Publicly available slow,2018,charging points,670.0
4,Australia,Historical,EV charging points,EV,Publicly available slow,2019,charging points,1700.0
5,Australia,Historical,EV charging points,EV,Publicly available slow,2020,charging points,2300.0
6,Australia,Historical,EV charging points,EV,Publicly available fast,2021,charging points,320.0
7,Australia,Historical,EV charging points,EV,Publicly available slow,2021,charging points,2000.0
8,Australia,Historical,EV charging points,EV,Publicly available fast,2022,charging points,470.0
9,Australia,Historical,EV charging points,EV,Publicly available slow,2022,charging points,2100.0
10,Australia,Historical,EV charging points,EV,Publicly available fast,2023,charging points,660.0
11,Australia,Historical,EV charging points,EV,Publicly available slow,2023,charging points,2100.0
12,Austria,Historical,EV charging points,EV,Publicly available fast,2011,charging points,0.1
13,Austria,Historical,EV charging points,EV,Publicly available slow,2011,charging points,0.1
14,Austria,Historical,EV charging points,EV,Publicly available fast,2012,charging points,0.1
15,Austria,Historical,EV charging points,EV,Publicly available slow,2012,charging points,0.1
16,Austria,Historical,EV charging points,EV,Publicly available fast,2013,charging points,0.1
17,Austria,Historical,EV charging points,EV,Publicly available slow,2013,charging points,0.1
18,Austria,Historical,EV charging points,EV,Publicly available fast,2014,charging points,0.1
19,Austria,Historical,EV charging points,EV,Publicly available slow,2014,charging points,0.1

In [7]:
for col in charging_df.columns:
    print(charging_df[col].unique())

['Australia' 'Austria' 'Belgium' 'Brazil' 'Canada' 'Chile' 'China'
 'Denmark' 'EU27' 'Europe' 'Finland' 'France' 'Germany' 'Greece' 'Iceland'
 'India' 'Indonesia' 'Israel' 'Italy' 'Japan' 'Korea' 'Mexico'
 'Netherlands' 'New Zealand' 'Norway' 'Poland' 'Portugal' 'South Africa'
 'Spain' 'Sweden' 'Switzerland' 'Thailand' 'Turkiye' 'United Kingdom'
 'USA' 'World']
['Historical']
['EV charging points']
['EV']
['Publicly available fast' 'Publicly available slow']
[2017 2018 2019 2020 2021 2022 2023 2011 2012 2013 2014 2015 2016 2010]
['charging points']
[4.00000000e+01 4.40000000e+02 6.10000000e+01 6.70000000e+02
 1.70000000e+03 2.30000000e+03 3.20000000e+02 2.00000000e+03
 4.70000000e+02 2.10000000e+03 6.60000000e+02 1.00000001e-01
 1.60000000e+03 8.90000000e+03 2.60000000e+03 1.30000000e+04
 2.50000000e+03 1.50000000e+04 4.70000000e+01 3.30000000e+02
 5.50000000e+01 5.60000000e+02 7.70000000e+01 1.30000000e+03
 1.10000000e+02 1.50000000e+03 2.20000000e+02 2.40000000e+02
 2.70000000e+03 3.60000000e+02 6.10000000e+03 4.80000000e+02
 8.00000000e+03 7.90000000e+02 1.20000000e+04 1.10000000e+03
 2.30000000e+04 4.20000000e+04 4.90000010e+00 2.60000000e+01
 4.00000000e+02 8.00000000e+02 3.00000000e+03 3.80000000e+03
 2.00000000e+00 7.20000000e+02 7.00000000e+00 1.20000000e+03
 6.30000000e+01 3.40000000e+03 1.40000000e+02 3.90000000e+03
 5.20000000e+03 8.40000000e+02 7.10000000e+03 9.80000000e+02
 1.10000000e+04 3.10000000e+03 1.70000000e+04 4.80000000e+03
 2.20000000e+04 1.00000000e+00 4.00000000e+00 6.00000000e+00
 5.00000000e+00 8.00000000e+00 1.30000000e+01 2.20000000e+01
 3.50000000e+01 4.20000000e+01 1.30000000e+02 9.90000000e+01
 1.20000000e+02 7.40000000e+02 9.00000000e+03 2.10000000e+04
 4.70000000e+04 5.50000000e+04 8.60000000e+04 8.30000000e+04
 1.30000000e+05 1.10000000e+05 1.60000000e+05 2.10000000e+05
 3.00000000e+05 3.10000000e+05 5.00000000e+05 4.70000000e+05
 6.80000000e+05 7.60000000e+05 1.00000000e+06 1.20000000e+06
 1.50000000e+06 3.00000000e+00 9.00000000e+02 5.60000000e+01
 9.90000000e+02 2.70000000e+02 3.10000000e+02 4.20000000e+03
 3.70000000e+02 3.90000000e+02 4.30000000e+03 4.50000000e+02
 4.50000000e+03 5.40000000e+03 7.00000000e+03 8.30000000e+03
 1.40000000e+04 7.30000000e+03 6.09999990e+00 5.90000000e+01
 6.90000000e+02 7.20000000e+04 8.10000000e+04 5.60000000e+03
 8.60000000e+03 9.80000000e+04 1.40000000e+05 1.90000000e+04
 1.80000000e+05 2.60000000e+05 2.90000000e+04 4.90000000e+04
 3.80000000e+05 5.10000000e+05 8.20000000e+04 3.20000000e+03
 2.40000000e+01 1.60000000e+02 1.60000000e+04 2.50000000e+04
 7.80000000e+02 1.40000000e+03 3.70000000e+04 5.90000000e+04
 5.70000000e+03 9.40000000e+04 9.30000000e+03 1.70000000e+05
 2.00000000e+04 3.00000000e+04 2.20000000e+05 4.30000000e+04
 6.80000000e+04 4.40000000e+05 5.90000000e+05 1.70000000e+01
 2.50000000e+02 7.10000000e+02 3.40000000e+02 1.80000000e+03
 4.10000000e+02 7.70000000e+02 5.80000000e+03 7.70000000e+03
 2.80000000e+03 9.00000000e+00 1.00000000e+02 5.80000000e+02
 9.90000000e+03 1.00000000e+03 2.80000000e+04 3.30000000e+03
 3.10000000e+04 5.00000000e+04 9.70000000e+03 7.40000000e+04
 1.80000000e+01 2.40000000e+03 4.60000000e+03 6.30000000e+02
 9.40000000e+03 2.60000000e+04 6.20000000e+03 7.10000000e+04
 8.70000000e+04 1.00000000e+01 1.40000000e+01 1.50000000e+01
 3.10000000e+01 1.90000000e+02 1.10000000e+01 3.60000000e+01
 3.20000000e+01 1.50000000e+02 2.90000000e+02 1.80000000e+02
 8.50000000e+02 2.50000000e+01 9.10000000e+02 4.10000000e+03
 6.80000000e+03 5.10000000e+01 5.00000000e+01 5.40000000e+01
 7.00000000e+01 1.70000000e+02 5.70000000e+02 2.90000000e+03
 8.60000000e+02 2.20000000e+03 6.50000000e+03 8.10000000e+03
 4.00000000e+04 6.00000000e+03 7.90000000e+03 8.40000000e+03
 9.60000000e+03 9.20000000e+02 1.00000000e+04 7.40000000e+03
 9.80000000e+03 9.20000000e+04 8.30000000e+01 7.00000000e+02
 7.60000000e+01 2.10000000e+01 1.80000000e+04 3.20000000e+04
 3.30000000e+04 8.20000000e+02 3.60000000e+04 4.60000000e+04
 6.30000000e+04 1.20000000e+05 2.00000000e+02 8.90000000e+01
 2.60000000e+02 4.30000000e+02 2.80000000e+02 5.80000000e+01
 3.70000000e+03 9.60000000e+01 5.00000000e+02 4.00000000e+03
 5.30000000e+03 6.70000000e+03 9.10000000e+03 4.90000000e+02
 5.30000000e+02 6.80000000e+02 4.40000000e+03 4.10000000e+01
 6.50000000e+02 3.70000000e+01 8.70000000e+01 8.10000000e+01
 9.10000000e+01 2.30000000e+02 6.00000000e+02 6.20000000e+02
 6.60000000e+03 5.50000000e+03 7.80000000e+03 2.70000000e+01
 3.50000000e+02 3.50000000e+03 1.90000000e+03 8.20000000e+03
 8.80000000e+01 6.90000000e+01 7.50000000e+02 3.00000000e+01
 5.20000000e+02 7.20000000e+03 6.90000000e+03 3.50000000e+04
 6.40000000e+04 1.00000000e+05 8.30000000e+02 4.10000000e+04
 8.90000000e+04 1.50000000e+05 2.40000000e+05 3.90000000e+05
 6.00000000e+05 8.70000000e+05 5.60000000e+05 9.00000000e+05
 1.80000000e+06 2.50000000e+06 1.40000000e+06]